name: Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy next-airbnb-clone to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18.x
        uses: actions/checkout@v2
        with:
          node-version: 18.x

      - name: Deploy to EC2 - SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: sh ./.github/scripts/deploy.sh
